# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Unity-iPhone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Unity-iPhone
  target 'Unity-iPhone Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
